-- POR CADA ADDREES DE LA PRIMERA TABLA MUESTRA TODOS LOS CLIENTES DE LA SEGUNDA TABLA
-- LO MUESTRA EN UN SET DE RESULTADOS COMBINA DATOS 1º CON 2º < REDIMIENTO 
SELECT * 
FROM address
CROSS JOIN customer;


-- es lo mismo que
SELECT * 
FROM address, customer;	
