-- CONSULTA RELACION DE MUCHOS A MUCHOS
#USE employees

SELECT * FROM employees
JOIN dept_emp USING(emp_no) #JOIN CON LA TABLA INERMEDIA 
JOIN departments USING(dept_no) #JOIN DE LOS CAMPOS CON LAS QUE SE RELACIONAN *-*