#MOSTRAR DESDE LA TABLA PAYMENT * Y DIFERENCIA ENTRE EL PAGO MAXIMO
SELECT payment_id, amount, (SELECT MAX(amount) FROM payment ) AS PAGO_MAXIMO,
		(SELECT PAGO_MAXIMO ) - amount AS DIFERENCIA
FROM payment  