#BUSCAR TODAS LAS PELICULAS DONDE AVG DEL RENTAL_RATE SEA SUPERIOR
#AL AVG DE TODAS LAS PELICULAS Y ORDENAR POR RENTAL_RATE

SELECT * FROM film
WHERE rental_rate > (SELECT AVG(rental_rate) FROM film)
ORDER BY rental_rate