SELECT * FROM employees
WHERE first_name LIKE 'ALE%'
#WHERE first_name LIKE '%A'
#WHERE first_name LIKE '%A%'
#COLOCAR UN PATRON DE BUSQUEDA QUE EMPIEZEN O TERMINEN POR ESE O CONTENGAN

#WHERE first_name LIKE '_A'#SOLO QUE TERMINE POR LA LETRA A Y QUE TENGA DOS CARATERES
# YA QUE EL _ SIGNIFICA QUE ES UN CARACTER

